### ISSUE TITLE
deformable convolution module

### ISSUE THREAD

**Issue by hangxiaotian** [zhaoyuzhi/D2HNet#1]
When installing the expansion convolution module, is there a requirement for the version of cuda and PyTorch?

**Comment by chenloveheimei** [comment]
你好，你这个问题如何处理？我现在也是这个模块报错

**Comment by zhaoyuzhi** [comment]
Yes, we use PyTorch 1.1 and CUDA 9.0.

After installing the environment, please try this:

```bash
cd dcn
python setup.py develop
```
