### ISSUE TITLE
Raw dataset

### ISSUE THREAD

**Issue by shekshaa** [zhaoyuzhi/D2HNet#3]
Hi,
First of all, thank you for sharing the code of this interesting code. I find it really helpful.
Second, I am wondering whether you can share the original HD videos you have used to create the tuples? I mean the data before computing averages to generate sharp and long exposure images.

**Comment by zhaoyuzhi** [comment]
Hi,

I update all the links in README file, please check: https://github.com/zhaoyuzhi/D2HNet#3-d2-dataset
The original videos are quite large to upload, please use youtube-dl to download those videos from the link

**Comment by shekshaa** [comment]
I see. Thank you.

**Comment by shekshaa** [comment]
By the way, I just realized that yt-dlp is much faster than youtube-dl for me. It reduces an hour ETA to a couple of minutes.
